### ISSUE TITLE
Removal of German specific Klar Privacy Notice doc

### ISSUE THREAD

**Issue by peiying2** [mozilla/legal-docs#1656]
Klar and Firefox Focus doc are now consolidated as a single [Firefox Focus PN](https://github.com/mozilla/legal-docs/blob/master/en/focus_privacy_notice.md), thus a German specific Klar doc is no longer needed. Legal asks to remove the following:
- https://github.com/mozilla/legal-docs/tree/master/en-DE
- https://github.com/mozilla/legal-docs/blob/master/de/klar_privacy_notice.md

**Comment by flodolo** [comment]
Fixed by #1668

**Comment by flodolo** [comment]
This might need an issue on the Bedrock side. I noticed that we unified the PN for Klar/Focus a while ago, but German is still showing the obsolete version in prod (it says "October" instead of "October 14"): https://www.mozilla.org/de/privacy/firefox-klar/

So there's probably code somewhere that searches for a klar document for German

**Comment by flodolo** [comment]
This is strange: the document is correct, because the title mentions both "Focus" and "Klar". But the date is incomplete, and the entire first paragraph is missing.

**Comment by flodolo** [comment]
Filed https://github.com/mozilla/bedrock/issues/10850
