### ISSUE TITLE
Auto-generate PDF copies of docs

### ISSUE THREAD

**Issue by clouserw** [mozilla/legal-docs#1778]
FxA does this for some documents at https://github.com/mozilla/fxa/blob/main/_scripts/legal-md-to-pdf.sh but it makes sense to provide PDFs in this repository to reduce human error as well as delay in document updates.

We don't need to do all documents (but we could) but at a minimum:
>  mozilla_vpn_privacy_notice.md
>  mozilla_vpn_tos.md
>  firefox_relay_tos.md
>  firefox_relay_privacy_notice.md
>  mdn_plus_privacy.md
>  mdn_plus_terms.md

If there are concerns about repository size these could live on a different branch although that would add to the complexity.  

A github action is probably the easiest way to do this.

**Comment by flodolo** [comment]
Since I had a POC for the conversion, I should be able to work on this when I'm back.

Questions:
* Does it matter where the PDFs are stored, e.g. is it OK to put them inside the .github folder so they don't show up in the root?
* Is it OK to only have them in the default branch, not the prod one?
* File structure and naming? e.g. 
  * LOCALE/FILENAME.pdf (it/mozilla_vpn_privacy_notice.pdf)
  * FILENAME/LOCALE.pdf (mozilla_vpn_privacy_notice/it.pdf)
  * FILENAME.LOCALE.pdf (mozilla_vpn_privacy_notice.it.pdf), i.e. flat structure

**Comment by clouserw** [comment]
I think it's up to us to answer (and document) those questions, so we'll let's make reasonable choices and go for it.  From my perspective:

For question 1 and 3:  Since we already have a %LOCALE%/%NAME%.pdf structure I would be inclined to keep that layout.  If you don't want PDFs cluttering up the same directories as the markdown files how about `%LOCALE%/pdf/%NAME%.pdf`.  That would be out of the way but still easy to find.  Combined with a little section in the README about how those are generated a person should be able to add new ones easily also.

For question 2:  I didn't even realize there was a prod branch, so, I don't have an opinion there.

**Comment by flodolo** [comment]
This was fixed in #1779 and #1782.
