### ISSUE TITLE
German version of Firefox + Cliqz privacy does not collapse correctly

### ISSUE THREAD

**Issue by dominiks-cliqz** [mozilla/legal-docs#944]
Looking at https://bedrock-demo-agibson.us-west.moz.works/de/privacy/firefox-cliqz/ the 3rd "learn more" ("mehr erfahren") link seems not quite right.

It reads "Weitere Informationen finden Sie in der Datenschutzerklärung Mehr erfahren von Cliqz. Wenn das Cliqz-Feature aktiviert ist, gilt Folgendes:".

I'd expect: "Weitere Informationen finden Sie in der Datenschutzerklärung von Cliqz. Mehr erfahren"

Then, after clicking on "Mehr erfahren" the following text should appear (together with the rest): "Wenn das Cliqz-Feature aktiviert ist, gilt Folgendes:" [...]

**Comment by alexgibson** [comment]
This is also the same in production, on the English version: https://www.mozilla.org/en-US/privacy/firefox-cliqz/

I think the issue is because there is already another link ("privacy policy") in the intro text. It should probably be tweaked so this link appears inside the expandable content instead.

**Comment by Algorithman** [comment]
cliqz equals LESS privacy. bye bye FF

**Comment by peiying2** [comment]
@dominiks-cliqz @alexgibson the file has been revised.  Take a look of the new version: https://bedrock-demo-privacy.us-west.moz.works/de/privacy/firefox-cliqz/

**Comment by dominiks-cliqz** [comment]
Thanks, @peiying2, the formatting looks good now!
